blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name = "index" ),
    path("post/<str:slug>", views.detail, name = "detail" ),
    path("contact", views.contact, name = "contact" ),
    path("about", views.about, name = "about" ),
    path("register", views.register, name = "register" ),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path,include

handler404="myapp.views.custom_page_not_found"

urlpatterns = [
    path("", include("blog.urls") ),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class AboutUs(models.Model):
    content = models.TextField()

blog/forms.py
from django import forms
from django.contrib.auth.models import User

class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100)
    email = forms.EmailField(label='Email')
    message = forms.CharField(label='Message')

class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='Username',max_length=100,required=True)
    email = forms.EmailField(label='Email',max_length=100,required=True)
    password = forms.CharField(label='Password',max_length=100,required=True)
    password_confirm = forms.CharField(label='Confirm Password',max_length=100,required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
            cleaned_data = super().clean()
            password = cleaned_data.get("password")
            password_confirm = cleaned_data.get("password_confirm")

            if password and password_confirm and password != password_confirm:
                raise forms.ValidationError("Password does not match")

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import Post, AboutUs
import logging
from django.core.paginator import Paginator
from .forms import ContactForm, RegisterForm
# posts = [
#             {'id':1,'title':"Post 1","content":"Content of Post 1"},
#             {'id':2,'title':"Post 2","content":"Content of Post 2"},
#             {'id':3,'title':"Post 3","content":"Content of Post 3"},
#             {'id':4,'title':"Post 4","content":"Content of Post 4"}
#     ]
# Create your views here.
def index(request):
    blog_title = "Latest Posts"
    posts = Post.objects.all()
    paginator = Paginator(posts,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'blog/index.html',{'blog_title': blog_title,'page_obj': page_obj})

def detail(request, slug):
    # post = next((item for item in posts if item['id']==int(post_id)),None)
    # logger = logging.getLogger("TESTING")
    # logger.debug(f"Post variable is {post}")
    post = Post.objects.get(slug=slug)
    related_posts = Post.objects.filter(category=post.category).exclude(pk=post.id)
    return render(request,'blog/detail.html',{"post":post,"related_posts":related_posts})

def contact(request):
        if request.method == 'POST':
            form = ContactForm(request.POST)
            name = request.POST.get('name')
            email = request.POST.get('email')
            message = request.POST.get('message')
            
            logger = logging.getLogger("TESTING")
            if form.is_valid():
                logger.debug(f"Post Data is {form.cleaned_data['name']} {form.cleaned_data['email']} {form.cleaned_data['message']}")
                success_msg = "Your Email has been sent!"
                return render(request,'blog/contact.html',{'success_msg':success_msg})
            else:
                logger.debug("Form validation failure ...")
            return render(request,'blog/contact.html', {'form':form, 'name': name, 'email': email, 'message': message})                 
        return render(request,'blog/contact.html')

def about(request):
     about_content = AboutUs.objects.first()
     if about_content is None or not about_content.content:
          about_content = "Default content goes here ..."
     else:
          about_content = about_content.content
     return render(request, 'blog/about.html',{'about_content':about_content})

def register(request):
     form = RegisterForm()
     if request.method == "POST":
          form = RegisterForm(request.POST)
          if form.is_valid():
               user = form.save(commit=False)
               print('Register Success!')
               user.set_password(form.cleaned_data['password'])
               user.save()
     return render(request,'blog/register.html',{'form':form})

myapp/views.py
from django.shortcuts import render
def custom_page_not_found(request,exception):
    return render(request,"404.html",status=404)

blog/templates/blog/about.html
{% extends "blog/base.html" %}{% block content %}
    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="About">
            <div class="content">{{about_content}}</div>
            
        </div>
    </div>
{% endblock %}%}   

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_title | default:"Document"}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

</head>
<body style="background-color: #cccccc;" >
    {% comment %} Header {% endcomment %}
    {% include "blog/includes/header.html" %}
  
  
    {% comment %} Dynamic content {% endcomment %}
    {% block content %}
    {% endblock  %}

        {% comment %} Footer {% endcomment %}
    {% include "blog/includes/footer.html" %}

 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/contact.html
{% extends "blog/base.html" %} {%block content%}
<div class="container-fluid">
  <div class="d-flex justify-content-center mt-5">
    <div class="d-flex gap-3 flex-column">
      <h3>Contact Form</h3>

        {% comment %} error message {% endcomment %}

      {%for field in form%} {%if field.errors%}
      <div class="col-12">
        <span class="fw-bold">{{field.label_tag}}</span>
        {%for error in field.errors%}
        <span class="text-danger">{{error}}</span>
        {%endfor%}
      </div>
      {% endif %} {%endfor%}

      <!-- success msg -->
      {% if success_msg %}
        <div class='alert alert-success' role='alert'>{{success_msg}}</div>
      {% endif %}

      <form method="post" class="row g-3">
        {% csrf_token %}
        <div class="col-md-6">
          <label for="name" class="form-label">Name</label>
          <input
            type="text"
            class="form-control"
            id="name"
            name="name"
            value="{{name}}"
          />
        </div>
        <div class="col-md-6">
          <label for="email" class="form-label">Email</label>
          <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            value="{{email}}"
          />
        </div>
        <div class="col-12">
          <label for="message" class="form-label">Message</label>
          <textarea
            class="form-control"
            id="message"
            name="message"
            rows="4"
            value="{{message}}"
            
          ></textarea>
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>
{%endblock%}

blog/templates/blog/detail.html
{% extends "blog/base.html" %} 
{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8">
      <h1 class="mb-4">{{post.title}} <small style="font-size:18px">({{post.category.name}})</small></h1>
      <p class="text-muted">Posted on {{post.created_at|date:"F j, Y"}}</p>
      <img
        src="{{post.img_url}}"
        class="img-fluid mb-4"
        alt="Blog Image"
      />
      <p>{{post.content}}</p>
    </div>
    <div class="col-lg-4">
      <div class="card mt-3">
        <div class="card-body">
          <h5 class="card-title">Related Posts</h5>
          <ul class="list-unstyled">
            {% for related_post in related_posts %}
            <li><a href="{% url "blog:detail" slug=related_post.slug %}">{{related_post.title}}</a></li>
            {%endfor%}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock%}

blog/templates/blog/includes/footer.html
<footer class="bg-dark text-light p-3">
    <div class="col-4 d-flex justify-content-center align-items-center">
      <span class="text-light">© 2024 Company, Inc</span>
    </div>
</footer>

blog/templates/blog/includes/header.html
<header class="p-3 bg-dark text-white">
    <div class="row">
        <div class="col">
            <a href="/" class="text-light text-decoration-none"><h3>Tenzo Blog</h3></a>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center gap-3">
                <a class="text-light text-decoration-none" href="/">Home</a>
                <a class="text-light text-decoration-none" href="/about">About</a>
                <a class="text-light text-decoration-none" href="/contact">Contact</a>
            </div>
        </div>
    </div>
</header>

blog/templates/blog/index.html
{% extends "blog/base.html" %} 
{% block content %}
<div class="container-fluid">
  <div class="row my-2">
    <div class="col">
      <h2>{{ blog_title | upper }}</h2>
    </div>
    <div class="col-3">
      <div class="input-group">
        <input
          type="text"
          class="form-control"
          placeholder="Search..."
          aria-label="Search"
        />
        <button
          class="btn btn-outline-light btn-primary"
          type="button"
          id="button-search"
        >
          <i class="bi bi-search"></i>
        </button>
      </div>
    </div>
  </div>
  <div class="row m-3">
    {% if page_obj %}
      {% for post in page_obj %}
      <div class="col-4 mb-4">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-md-4">
                <img
                  style="height:300px;width:300px"
                  src="{{ post.img_url }}"
                  class="img-fluid"
                  alt="..."
                />
              </div>
              <div class="col-md-8">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.content|truncatechars:50 }}</p>
                <div class="d-flex justify-content-between">
                  <a href="{% url 'blog:detail' slug=post.slug %}">Read More</a>
                  <a class="text-decoration-none text-dark fw-bold" href="#">
                    {{ post.category.name }}
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      <div class="col-12 my-3">
        {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation">
          <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1" aria-label="First">
                <span aria-hidden="true">&laquo; first</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">previous</span>
              </a>
            </li>
            {% endif %}
            <li class="page-item">
              <span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span>
            </li>
            {%if page_obj.has_next%}
            <li class="page-item">
              <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                <span aria-hidden="true">next</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                <span aria-hidden="true">last &raquo;</span>
              </a>
            </li>
            {%endif%}
          </ul>
        </nav>
        {% endif %}
      </div>
    {% else %}
      <p>No posts Available ...</p>
    {% endif %}
  </div>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends "blog/base.html" %} 
{% block content %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Register</h3>
                <div class="">    

                    {%for field in form%} {%if field.errors%}
                    <div class="col-12">
                        <span class="fw-bold">{{field.label_tag}}</span>
                        {%for error in field.errors%}
                        <span class="text-danger">{{error}}</span>
                        {%endfor%}
                    </div>
                    {% endif %} {%endfor%}

                    {% for field in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <span class="text-danger">{{field}}</span>
                        </div>
                    {% endfor %}
                 </div>
                <div class="my-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{form.username.value|default:""}}">
                        </div>
                        <div class="form-group">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{form.email.value|default:""}}">
                        </div>
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                        <div class="form-group">
                            <label for="confirm_password" class="form-label">Confirm Password</label>
                            <input type="password" class="form-control" id="confirm_password" name="password_confirm">
                        </div>
                        <div class="my-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}